<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="PRG_LVCP5" Id="{18ab8ba3-8ac4-4e40-a325-116379e8dbfa}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_LVCP5
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[	PRG_LVCP5_PowerMeasurement();

	PRG_LVCP5_CompensationCalculate();

	PRG_LVCP5_MainCircuitBreaker();
	
	PRG_LVCP5_Group1();
	
	PRG_LVCP5_Group2();
	
	PRG_LVCP5_Group3();	
	
	PRG_LVCP5_Group4();	

	PRG_LVCP5_Group5();	

	PRG_LVCP5_Group6();	

	PRG_LVCP5_Group7();		]]></ST>
    </Implementation>
    <LineIds Name="PRG_LVCP5">
      <LineId Id="29" Count="1" />
      <LineId Id="25" Count="0" />
      <LineId Id="6" Count="0" />
      <LineId Id="5" Count="0" />
      <LineId Id="7" Count="0" />
      <LineId Id="13" Count="11" />
      <LineId Id="8" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>